version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  redpanda:
    image: redpandadata/redpanda:v23.3.11
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - --advertise-kafka-addr INTERNAL://redpanda:9092,EXTERNAL://localhost:29092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "29092:29092"
      - "9644:9644"
      - "8082:8082"

  redpanda-console:
    image: redpandadata/console:latest
    ports:
      - "8085:8080"
    environment:
      # Tell the console to use the internal Docker container address
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda

volumes:
  postgres_data:
  grafana_data: